### ISSUE TITLE
Doesn't deploy on server despite hook works seemingly

### ISSUE THREAD

**Issue by bertalanimre** [orphans/git-deploy-laravel#1]
Hy There,

1stly thank you for making this laravel deployment for GitLab. This could make our job faster and more precise. However I have a problem, could you help me?
I use GitLab and installed your sollution as you've explained. Wasn't hard, loved the easiness of it. On gitlab I can test if it can reach and execute the hook. It sais OK. But whenever I push something from my local computer to the repository, it doesn't get pulled to the server.
What do you need to have a clue? I use Laravel 5.1 Framework and GitLab 8.4

I've made a custom configuration according to your manual and set only a server repository.

Oh and BTW: \config\gitdeploy.php ? You should reverse the prior. :) On linux it is the other way around!

**Comment by Muffinman** [comment]
Hi,

Are you able to do a pull from the server manually without any errors?

Just to rule out any modified files etc.

**Comment by bertalanimre** [comment]
Yes, manual git pull works like a charm. I added you to the project, I think you are able to pull it down now?

**Comment by Muffinman** [comment]
Hmm no I don't think the user level you've given has access to clone to code (can't see the files tab on gitlab.com either).

I've take another look at our code and there's several things that could cause the problem.

Due to an oversight on our part, the remote is hard coded to `origin` and the branch you are using on the server has to be `master`. We'll move these into the config in the next version.

You'll also need shell_exec enabled in PHP in order for the code to call git.

**Comment by bertalanimre** [comment]
Check permissions again please. And yes, I'm using the server as `origin master`. That should be fine.

**Comment by Muffinman** [comment]
Can you try swapping out the package to our development one?

```
    "orphans/git-deploy-laravel" : "dev-develop"
```

In your composer.json.

I've added the remote name into the config file, and made the pacakge log into storage/logs/gitdeploy.log for debugging.

**Comment by bertalanimre** [comment]
Did it. Doing the composer update. Then I should watch the log file while I push from a developer machine? And do I have to create the file or it will be created? (it doesn't exist after the update)

**Comment by Muffinman** [comment]
Sorry, can you do another `composer update`, just pushed some extra logging up. After that, the log file should appear on the first time the `/git-deploy` route is visited. e.g. after testing or using the webhook.

**Comment by bertalanimre** [comment]
```
$ composer update
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> php artisan optimize
Generating optimized class loader
```

I guess I did the update just in time before? :D Testing with a push now. BTW: What should I trigger the webhook to? Build or Push? I want to deploy if the build was succesfull, so I suppose Build what I need. Am I right?

**Comment by bertalanimre** [comment]
```
[2016-02-22 15:53:03] name.ERROR: Invalid repo path in config [] []
[2016-02-22 15:53:03] name.ERROR: Invalid repo path in config [] []
[2016-02-22 15:53:06] name.ERROR: Invalid repo path in config [] []
[2016-02-22 15:53:56] name.ERROR: Invalid repo path in config [] []
[2016-02-22 15:57:58] name.ERROR: Invalid repo path in config [] []
```

In my config file, I have this as repo name:
`'repo_path' => 'git@gitlab.com:bertalanimre/gitlab-skeleton.git',`

**Comment by Muffinman** [comment]
The right dev version should be bac7fc7. Likely you've already got the latest if it says no updates available.

We don't use build hooks ourselves here, but yes that sounds right? I guess it depends what data it sends down with that hook. Our code is looking for some specific data in the webhook request (latest commits, branch, refs etc.) which must be present.

**Comment by Muffinman** [comment]
Ah, yes I see the problem.

The `repo_path` variable should be set to the local server directory which contains the `.git` folder.

e.g.: `/home/user/gitlab-skeleton` or similar

You can also leave this blank and it will work as long as the .git folder is somewhere in a parent folder of the document root.

**Comment by bertalanimre** [comment]
I see, sorry for making that kind fo mistake. However, if I set the hook to build, then it doesn't do anything after a succesfull build. I'll try it now with a push event.

**Comment by Muffinman** [comment]
Hmm, Gitlab don't even list the build hook in their webhook events:

https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md

So I can't even tell what data it's going to send to the hook. Did you see anything in your gitlab.log after testing the build hook?

**Comment by bertalanimre** [comment]
Well, I might do something wrong. in my main folder I'm constantly editing a file newfile.txt. and pushing it to the repo, so it would be deployed to the webserver. I suppose, this is where the deployment should work. However, the log doesn't log anything, but the file is not pulled either. Not for any trigger events, (push or build)

**Comment by bertalanimre** [comment]
Strange, that they don't show the build-event trigger, it is in since 8. something.

**Comment by bertalanimre** [comment]
Is the log supposed to log even a succesfull atempt to pull?

**Comment by Muffinman** [comment]
Yes it should log the output of the git pull command, whatever that will be.

**Comment by bertalanimre** [comment]
It doesn't show anything. :/

**Comment by Muffinman** [comment]
Can you post the contents of your `config/gitdeploy.php` file now?

**Comment by bertalanimre** [comment]
Yes, 1 moment please:

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Email recipients
    |--------------------------------------------------------------------------
    |
    | The email address and name that notification emails will be sent to.
    | Leave the array empty to disable emails.
    |
    | [
    |     ['name' => 'Joe Bloggs', 'address' => 'email@example1.com'],
    |     ['name' => 'Jane Doe', 'address' => 'email@example2.com'],
    |     ...
    | ]
    |
    */

    'email_recipients' => [],

    /*
    |--------------------------------------------------------------------------
    | Email sender
    |--------------------------------------------------------------------------
    |
    | The email address and name that notification emails will be sent from.
    | This will default to the sender in config(mail.from) if left null.
    |
    */

    'email_sender' => ['address' => null, 'name' => null],

    /*
    |--------------------------------------------------------------------------
    | Repository path
    |--------------------------------------------------------------------------
    |
    | This the root path of the Git repository that will be pulled. If this
    | is left empty the script will try to determine the directory itself
    | but looking for the project's .env file it's nearby .git directory.
    |
    | No trailing slash
    |
    */

    'repo_path' => '',

    /*
    |--------------------------------------------------------------------------
    | Allowed sources
    |--------------------------------------------------------------------------
    |
    | A request will be ignored unless it comes from an IP listed in this
    | array. Leave the array empty to allow all sources.
    |
    | This is useful for a little extra security if you run your own Git
    | repo server.
    |
    */

    'allowed_sources' => [],

];
```

Testing now with absolute repo path:
`'repo_path' => '/var/www/repofolder',`

**Comment by Muffinman** [comment]
Hmm well that all looks correct, any errors in the main laravel.log?

**Comment by bertalanimre** [comment]
Nothing really. Now please stand by. I've installed my own GitLab server this time, and I'm gonna test it again. Question: When I go to the admin area in my own GitLab server, I can see a `deploy keys` menu, that is asking for a server key.
`Paste a machine public key here.`
What is this? Have you ever seen it?

**Comment by Muffinman** [comment]
This is usually in `~/.ssh/id_rsa.pub` of the user you are doing the git pull as.

If that file doesn't exist then you may need to run `ssh-keygen` as that user.

**Comment by bertalanimre** [comment]
So, if I usually git pull my project with the root user, I need to create a seperate ssh-key for the root user and add it as a deployment key to the project in order to be able to pull?

**Comment by Muffinman** [comment]
It depends on what user your webserver runs as. If your website repo and files are owned by root, then the webserver user will most likely not have permission to perform a git pull.

Remember that when the webhook url is called, the PHP is just executed on the server as the current user, and therefore any child processses are also executed as that user. In a standard apache setup this may be the `www-data` user or similar. It is this user that will need the SSH key generated, and the .pub file adding to GitLab.

For our own servers, we mostly run nginx + php-fpm or apache2 + php-fcgi, in both cases we have php set up to run as a user specific to that vhost. This means that PHP has permissions to do a git pull on it's own files.

**Comment by bertalanimre** [comment]
I see your point. We also use NginX and PHP-FPM. But in our case, the `apache` user ( who is currently set as the user for NginX) is a nologin user. How should I set him an SSH key? Just find out the home folder of the user, make a folder with some keys in it and put it there? Could that be enough?

**Comment by Muffinman** [comment]
Yes this may well be enough, even nologin users have home directories.

I'd be nervous about dropping keys into `/var/www` (the standard home dir for www-data) because on many setups that it by default a web accessible directory. 

A better approach may be to create a new user to 'own' the website files and alter the PHP user settings in `/etc/php5/fpm/pools.d/www.conf`

The lines you will need to change are:

```
user = www-data
group = www-data
```

Just change these to 

```
user = yournewusername
group = yournewusergroup
```

Then just change your nginx root to point to /home/yournewusername/subdirforwebsite

**Comment by bertalanimre** [comment]
Indeed. I'll start with this tomorrow, not even gonna shutdown my office computer. Currently trying this method on a local system but I'm starting to tear my hair out. But I think with your help, I can make it. :) Thanks in advance!

**Comment by Muffinman** [comment]
This also has the added benefit of not having to `chmod 777` any upload directories etc., because as long as everything is owned by that user then by default they'll have write access.

Good luck!

**Comment by bertalanimre** [comment]
So far I've created the new user on my local computer, created SSH keys for him, added to the server as deployent keys, cloned without a problem. Then the usual (composer install, env file, artisan key:generate, artisan migrate:refresh --seed, chmod on storage and bootstrap/cache, artisan vendor:publish, gulp) and the website is up'n running. So I wanted to add the webhook as you've written in your readme but whenever I try to test the hook, I always get a laravel 500 page. The PHP file is executeable, setting are as we've already discussed here, so I'm looking up what could cause the 500s error of Laravel. When that happens, I think we are good to go. 
BTW: I can pull other files as well, not just the files in public folder, am I?

**Comment by Muffinman** [comment]
Yes it will pull any files in the git repo as long it as it has permission to read / write the directories.

If you're getting 500 errors then can you post the output of the stack trace it gives you, or the contents of the laravel.log?

**Comment by bertalanimre** [comment]
The error is somewhere in my NginX config.
- If I try an URL directly to the PHP file in my browser, it succeds (tho it sais failed attempts, but that is the output of the PHP file).
- If I try an URL directly to the git-deploy link in my browser, it fails with an NginX 500 error. Sais something about `rewrite or internal redirection cycle while redirect to named location "@rewrite"`
- If I test the webhook for http://myserver.ip/deploy.php I get an 500 error
- If I test the webhook for http://myserver.ip/git-deploy I get an 500 error

Digging it now. (Laravel logs don't show anything. and the gitdeploy.log is not present as well.)

**Comment by bertalanimre** [comment]
OK, found it... now tying to fix it. 

```
Errno::EHOSTUNREACH (No route to host - connect(2) for "myserver.ip" port 80):
  app/models/hooks/web_hook.rb:41:in `execute'
  app/services/test_hook_service.rb:4:in `execute'
  app/controllers/projects/hooks_controller.rb:28:in `test'
```

**Comment by bertalanimre** [comment]
I don't know if I did it by mistake, or it actually worked, but I think I've done it. Can you do me a favour?
I want to put a timestamp into the `gitdeploy.log` file to see when did it try the pull. Can you make that happen? In bash I know it looks like this:
`echo $(date +%Y%m%d_%H%M)`

**Comment by bertalanimre** [comment]
I have an idea. I can make a script run after a succesfull build in my `.gitlab-ci.yml`. How about if I ask a script to start your script? Or even better, we could try to implement your script into this file, then it will be executed ONLY after a succesfull test build. What do you think?

**Comment by Muffinman** [comment]
Well the git pull will always need to be executed on the remote side, but there's no reason you cant call the hook yourself as long as the right POST data is supplied.
