### ISSUE TITLE
Empty postdata when deploying from github

### ISSUE THREAD

**Issue by sigrtmax** [orphans/git-deploy-laravel#14]
In file vendor/orphans/git-deploy-laravel/src/http/GitDeployController.php line 46 should be 
$postdata = json_decode($request->get('payload'), TRUE);
if you are using github
Tested via laravel 5.7

**Comment by Muffinman** [comment]
Hi @alapaev,

Thanks for the report, I believe we followed the specs for GitHub payloads as per [this page](https://developer.github.com/v3/activity/events/types/#pushevent). As far as I know this is tested and working?

Your suggestion assumes that the data is sent in a GET/POST variable called `payload`, can you give me an example webhook request payload where this change works for you?

**Comment by sigrtmax** [comment]
Sure, example on screenshot https://i.imgur.com/zrWYiAn.png

**Comment by sigrtmax** [comment]
With present version of code webhook gets this json from my webserver
{"success":false,"message":"Web hook data does not look valid"}

**Comment by Muffinman** [comment]
Ah, I think you might be sending with the wrong content type.

It should be sent with `application/json` rather than `application/x-www-form-urlencoded`. I'll have to add a note about this in the docs.

**Comment by Muffinman** [comment]
Example page from Github webhook setup:

![screen shot 2019-02-05 at 22 52 21](https://user-images.githubusercontent.com/1319568/52309653-b92cce80-2998-11e9-8480-e18b66ddc655.png)

**Comment by sigrtmax** [comment]
Thanks a lot! I've missed this input in form
