### ISSUE TITLE
GitDeploy is not working with Laravel 5.5

### ISSUE THREAD

**Issue by tux-tn** [orphans/git-deploy-laravel#7]
Hello,

Gitdeploy was working perfectly but after migrating our project from Laravel 5.4 to Laravel 5.5 our webhook stopped working as you can see in the screenshot

![capture d ecran de 2017-10-26 20-10-26](https://user-images.githubusercontent.com/1423022/32072252-dc9e79f6-ba89-11e7-809c-c80cd713f262.png)

**Comment by Muffinman** [comment]
Hmm, I'm not sure what this could be. We're using this on quite a few Laravel 5 projects without any issues.

Can you double check the provider is in your `config/app.php`? We haven't implemented the new 5.5 package discovery yet so this is still required.

Are you able to post the full stack trace if this is not the issue?

**Comment by Muffinman** [comment]
Closing this, feel free to re-open if still having issues.

P.S. I've since implemented the 5.5 package discovery.
