### ISSUE TITLE
Template & Security

### ISSUE THREAD

**Issue by Nowi5** [orphans/git-deploy-laravel#8]
Hi all,

while looking for a nice webhook, I came across your package. And without having it installed I ask myself how you manage the security e.g. with tokens so that not everybody could call your script?
Further I miss the maintenance mode or the script to have updates without downtime. Maybe I missed something? Some templates, examples, for your config would really improve the package.

Thank you.

**Comment by Muffinman** [comment]
Hi, thanks for your feedback.

Security is achieved in the form of IP restriction from the pushing server, as per the config file: https://github.com/orphans/git-deploy-laravel/blob/master/config/gitdeploy.php#63

I am aware that Gitlab now supports security tokens as part of the webhook request, which is certainly something we should look at implementing.

Also your idea about the maintenance mode is a good one, we mainly use this for our own projects where a couple of seconds downtime is not a big issue, but I can certainly see that this would be a nice feature to add.

**Comment by Muffinman** [comment]
Hi @Nowi5, thanks for your comments and suggestions, going to give these new features a try on a few sites before I tag a release.

Let me know if you have any problems.

P.S. I updated the [README](https://github.com/orphans/git-deploy-laravel/blob/master/README.md) with the config options available, hopefully this is more clear!

**Comment by Nowi5** [comment]
Thank you very much.

Maybe stupid question, but I'm not very used to Git until now.
How can I get the newest code, to support testing without a new tag?
I use composer to install and followed "composer require orphans/git-deploy-laravel".

In addition the config file looks very good. However you could increase it a bit more;
For example that 'allowed_sources' => [], is an IP like '8.8.8.8' and if you support IPv6 or not.
Or the  'remote' => 'origin', Is origin same as master. When I have on gitlab multiple branches like master and production, can I say here production only?

Thank you.

**Comment by Muffinman** [comment]
To install the dev version just require the dev version of the package like so:

`composer require orphans/git-deploy-laravel:dev-master`

The IP checks just use the `REMOTE_ADDR` server variable, so if your web server is listening on IPv6 and your client requests with IPv6 then you will need an IPv6 address in the config file. As it's very dependent on the user's particular setup I'm not sure there's much merit to it being specifically documented.

For the branch query, the code checks that the branch being pushed to matches the branch the Laravel code is currently running on. So if you rush your live sites on a `production` branch then only a push to the `production` branch will cause a deployment to the server.

Hope that helps!
